# Generated by Django 3.2.25 on 2024-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': '3 About Us',
            },
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '2 Terms & Condition',
            },
        ),
        migrations.CreateModel(
            name='WallpaperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('owner', models.TextField(max_length=200)),
                ('contact', models.URLField()),
                ('description', models.TextField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '1 Wallpaper_Info',
                'ordering': ['-upload_date'],
            },
        ),
    ]
