# Generated by Django 3.2.25 on 2024-08-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaperinfo',
            old_name='owner',
            new_name='name',
        ),
    ]
